name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest -f ./Dockerfile ./myapp  # Explicitly specify Dockerfile path

      - name: Run Tests
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:latest npm test  # Run tests inside the container

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v1
        with:
          railwayProjectId: ${{ secrets.RAILWAY_PROJECT_ID }}  # O ID do seu projeto Railway
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}  # Token de acesso do Railway
          dockerImage: ghcr.io/${{ github.repository }}:latest  # Imagem a ser usada no Railway

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}  # Tag com base no número da execução
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso ao GitHub
