name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest -f ./Dockerfile ./myapp  # Explicitly specify Dockerfile path

      - name: Run Tests
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:latest npm test  # Run tests inside the container

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Install Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Set the Railway token as an environment variable
        run: railway up --projectId ${{ secrets.RAILWAY_PROJECT_ID }} --image ghcr.io/${{ github.repository }}:latest

      - name: Create Release
        run: |
          git tag -a "v$(date +'%Y%m%d%H%M%S')" -m "Release on $(date)"
          git push origin --tags

