name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .
          docker tag myapp:${{ github.sha }} mydockerhubusername/myapp:latest
          docker push mydockerhubusername/myapp:latest

      - name: Deploy to server
        run: |
          ssh user@server-ip "docker pull mydockerhubusername/myapp:latest && docker run -d -p 3000:3000 mydockerhubusername/myapp:latest"
